-- migrate:up
CREATE TABLE hosts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT hosts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
)


-- migrate:down
DROP TABLE IF EXISTS hosts
